name: Native Test

on:
  push:
  pull_request:

jobs:
  native-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build native test
        run: make native-test
